project:
  type: website

website:
  #title: "Wenhong (Tony) Sun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Bio
      - href: projects.qmd
        text: An

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



