---
#title: "Coursework"
---

## Coursework at UCLA


#### **Mathematics**
###### Upper Division
- Math 115A: Linear Algebra
- Math 131A: Analysis I
- Math 131B: Analysis II
- Math 132: Complex Analysis for Applications
- Math 151A: Applied Numerical Methods
- Math 164: Optimization
- Math 171: Stochastic Processes *(Winter 2025)*
- Math 174E: Mathematics of Finance for Mathematics/Economics Students
- Math 179: Advanced Topic in Financial Mathematics
- Math 195: Community Internships in Mathematics Education

###### Lower Division
- Math 32A: Calculus of Several Variables I
- Math 32B: Calculus of Several Variables II
- Math 33A: Linear Algebra and Applications
- Math 33B: Differential Equations
- Math 42: Introduction to Data-Driven Mathematical Modeling: Life, Universe, and Everything
- Math 61: Introduction to Discrete Structures

#### **Statistics and Data Science**
###### Upper Division
- Math 170E: Introduction to Probability and Statistics 1: Probability
- Math 170S: Introduction to Probability and Statistics 2: Statistics
- Stats 100C: Linear Models
- Stats 101A: Introduction to Data Analysis and Regression
- Stats 101B: Introduction to Design and Analysis of Experiment
- Stats 101C: Introduction to Statistical Models and Data Mining
- Stats 102A: Introduction to Computational Statistics with R
- Stats 102B: Introduction to Computation and Optimization for Statistics
- Stats 102C: Introduction to Monte Carlo Methods
- Stats 140XP: Practice of Statistical Consulting I 
- Stats 141XP: Practice of Statistical Consulting II

###### Lower Division
- Stats 10: Introduction to Statistical Reasoning
- Stats 20: Introduction to Statistical Programming with R
- Stats 21: Python and Other Technologies for Data Science

#### **Economics**
###### Upper Division
- Econ 101: Microeconomic Theory
- Econ 102: Macroeconomic Theory
- Econ 103: Introduction to Econometrics
- Econ 103L: Econometrics Laboratory
- Econ 106F: Finance
- Econ 106FB: Finance Laboratory
- Econ 160: Money and Banking
- Econ 162: Monetary Policy 

###### Lower Division
- Econ 11: Microeconomic Theory

#### **Computer Science**
###### Lower Division
- CS 31: Introduction to Computer Science I (C++)
- PIC 10A: Introduction to Programming (C++)

#### **General Education**
- Cluster 70A: Evolution of Cosmos and Life
- Cluster 70B: Evolution of Cosmos and Life
- Cluster 70CW: Evolution of Cosmos and Life: Special Topics in Life and Physical Sciences: Science and Technology during Cold War
- ENGCOMP 3: English Composition, Rhetoric, and Language
- Pub Aff 10: Social Problems and Social Change
- CHIN 50: Chinese Civilization
- LING 1: Introduction to Study of Language
- LBR STD 10: Introduction to Labor and Workplace Studies
- CESC 50XP: Engaging Los Angeles






